### ISSUE TITLE
Generate deterministic results by providing a seed

### ISSUE THREAD

**Issue by nlochschmidt** [json-schema-faker/json-schema-faker#111]
The use case that I am thinking about is that of a stateless mock server. The mock server could take some data from a request, e.g. some HTTP headers + query parameter + request body and calculate a seed. That seed would then be used for generating a json response using jsf. That way when calling the mock several times in the exact same way it would respond with the same result every time.

As far as I see it Faker and Chance already allow setting a seed. So it shouldn't be much effort and I would volunteer providing a PR if you think it is useful. However my question would be how the seed should be provided. In an `options` parameter on the `generate` method?

What do think?

**Comment by ducin** [comment]
Hello @nlochschmidt, thanks for your thought. At a first shot I think this might be more related to https://github.com/json-schema-faker/json-schema-server project. We try to keep things separated, and so `jsf` is used only for generating the data, whereas a stub server shall be something more that might or might not rely on `jsf`.

Moreover, I think that this `some HTTP headers + query parameter + request body` is exactly what [RAML](raml.org), [swagger](swagger.io) and [API Blueprint](https://apiblueprint.org/) define.

So from my point of view:
* the idea you mentioned makes sense, but it's more into `json-schema-server`. I hope @pateketrueke will share his opinion on the seeds
* and regarding `some HTTP headers + query parameter + request body` - I'm very much into this topic and I was thinking of combining our `jsf` first with RAML then with swagger. I see great future in a combination like that. But this would not be one commit, rather, a whole project. Would you have time and would you like to join our team working on it?

**Comment by nlochschmidt** [comment]
First of all, thanks for making me aware that what I actually want to do is to stub and not mock a server. Also thanks for the pointer to [json-schema-server](https://github.com/json-schema-faker/json-schema-server). I will look into it.

Setting a seed in jsf manually would still be required to make this work in json-schema-server, right?

I am not so sure that RAML, Swagger, etc are the way to go for stubbing an API during development. At least for internal APIs, I would not go through the trouble of creating and maintaining a complete API specification. In addition I am thinking about mixing a little bit of simulated behavior into the stub inspired by the way [Interfake](https://github.com/basicallydan/interfake) works. I don't see that working well with RAML and the like.

**Comment by ducin** [comment]
Hmm, well, don't know what you mean by "internal" or "external" API. In my opinion RAML, swagger, etc. - indeed are a good way to stub an API, since whatever client (web, mobile) you develop, you communicate somehow anyway. Apart from generating docs, you also get client/server scaffolding, backend auto-tests and fake data servers... but they're not integrated with `jsf` yet :) As far as I see, Interfake does exactly the same as RAML/swagger/etc but is just less formal. And either you use JavaScript (code) or stick to [yet another syntax to define the same as RAML or swagger](https://github.com/basicallydan/interfake/wiki#example-more-examples-1). If you want to define URLs, http methods, statuses, etc - you do it in interfake anyway, but have less tools support.

Could you provide more details what exactly do you mean by *mixing a little bit of simulated behavior into the stub*?

**Comment by nlochschmidt** [comment]
By internal API, I am referring to APIs provided from one (micro)service to another inside our application. Both consumer and provider of the API are completely under our control, so we decide when they go live, etc. In addition, most of the time the consumer specifies the API requirements and there maybe multiple consumers for the same API (see [consumer contract testing](http://martinfowler.com/articles/microservice-testing/#testing-contract-introduction)). 

Contract tests are very limited in that they should not test actual behavior across multiple requests, however during development it is still sometimes useful to stub a little bit of behavior e.g. when POSTing an item it should be added to the response of a GET to the corresponding index. In interfake that would look like this:
```javascript
interfake.get('/items').status(200).body({ items: [ { id: 1, name: 'Item 1' } ] });
var postResponse = interfake.post('/items').status(201).body({ created : true });
postResponse.extends.get('/items').status(200).body({ items: [ { id: 2, name: 'Item 2' } ] });
```
The last line `extends` the previously defined `/items` endpoint to return an additional item. I am not sure that can be described in RAML.

Another question with the RAML stub server approach is how to decide between different example responses available in the RAML file. So when an endpoint can return 200 or 404 depending on the user state, how do I decide that in the stub when all I have is a RAML file.

Anyways, thanks for the great discussion even though this goes far away from my feature request :smile:

**Comment by pateketrueke** [comment]
If we can setup a seed over jsf and produce the same values many times, regardless of its application, sounds awesome. :beers:

> However my question would be how the seed should be provided. In an options parameter on the generate method?

Actually jsf doesn't make use of any `options` object, but there are related issues that can be solved by configuration, e.g. https://github.com/json-schema-faker/json-schema-faker/issues/81#issuecomment-159087484

As a missing feature I think it would help a lot, and since the `refs` [is expected to be an array](https://github.com/json-schema-faker/json-schema-faker/blob/master/lib/jsf.js#L13) it would not break anything...

**Comment by pateketrueke** [comment]
Guys, the `develop` branch is now stable.

So, it is possible to provide a seed for achieve the same results all the time? 🤔

**Comment by alequetzalli** [comment]
Is there any update about being able to setup a seed ? Still in the works or..?

**Comment by pateketrueke** [comment]
> Is there any update about being able to setup a seed ? Still in the works or..?

I would like to include that feature in the next versions of `jsf` but I don't have any clue on this topic.

Do you have any hint on how we can achieve this? 

Thanks for your feedback!

**Comment by javiercejudo** [comment]
Deterministic results are now possible in [v0.4.3](https://github.com/json-schema-faker/json-schema-faker/releases/tag/v0.4.3) via #307, which was a backport of #305. Here is the gist of it:

```js
const jsf = require('json-schema-faker');
const seedrandom = require('seedrandom');

jsf.option({
  random: seedrandom('some seed')
});
```

**Comment by nlochschmidt** [comment]
I haven't tried it yet, but it looks exactly like what I described.
Kudos @javiercejudo 🙇
