### ISSUE TITLE
Combine strings

### ISSUE THREAD

**Issue by be-codified** [json-schema-faker/json-schema-faker#125]
Hi,

is there a way to combine generated strings?

Something like this:
```
randomTime: {
  type: 'string',
  faker: 'hours' + ':' + 'minutes',
},
```

**Comment by ducin** [comment]
Do you mean that you'd like to have something like this:

```
{
  minute: 5
  hour: 11
  time: "11:05"
}
```
? Or like this:
```
{
  firstName: "John"
  lastName: "Doe"
  fullName: "John Doe"
}
```
where firstName, lastName are raw generated pieces and fullName is just combined using them?

If not, please give more details on what you aim.

**Comment by be-codified** [comment]
Thank you for reply, you are reading my mind.

**Comment by ducin** [comment]
That's a big shame for us, since we've been thinking about this since quite a while, see #11. It's quite easy to do for simple objects, but it's complex for bigger objects (where you re-use nested values or siblings). So we prefer to support either all or nothing.

So I close this one in favor of #11. @be-codified would you like to help us in developing json-schema-faker :)? If so, please contact us via email.
