### ISSUE TITLE
dist directory size, git slowing down and becoming sluggish

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#133]
@pateketrueke we made a mistake.

![image](https://cloud.githubusercontent.com/assets/375027/14365592/f05ff562-fd0e-11e5-82b6-a4765fe2c710.png)

The lines of code added and removed are greatly increased because of the dist products which are kept in our repo. We wanted to provide single-language faker builds, generically for npm, bower, cdn.js etc. - and that is very cool - but it's too heavy.

I can see that my local repo is slowing down on every `git diff`, `git status`, etc. and it's gonna be worse and worse each release. Additionally, when I was adding cdn.js integration, I saw that cdn.js team is experiencing exactly the same issue, but on a larger scale. And they have to do voo-doo magic to get by. And I want to avoid that :)

I'm curious what you think about this. However, I do have an idea on how to solve that:
1. create a mirror repo e.g. `json-schema-faker-dist` which would include only the distributions (current `dist` directory).
2. migrate all cdn.js-existent, `dist` things there
3. switch our cdn.js settings to pull the new cdn.js version from the new repo
4. when everything is done, remove all builds from our source repo, and that is:
4.1. inform everyone that forked the repo (easy to list on github) that all branches will get rewritten (push --force) and all their branches will get diverged -> need to re-clone the whole repo. Set up the timer for this action.
4.2 execute it, when the time comes.

I'll check that with cdn.js team.

**Comment by pateketrueke** [comment]
Regardless the repo size we can mark those dist files as binaries?

I think the slow thing is only about how git works with source files, I mean, that not happens with tons of images for say something?

I'm not sure if that can be a solution, otherwise we can try an alternative repository.

**Comment by ducin** [comment]
I'm not sure if marking js files as binary is a good approach, dunno. I got no fucking idea how bower is gonna serve such files, when someone fires `bower install json-schema-faker`. Woudln't it break anything?

My local repository weights almost 400MB :( that is way too much. It's gonna weight a lot more if we release often (and I guess we would like to). Binaries wouldn't change anything here I guess?

How much disk space does your repo hold?

**Comment by DanielJoyce** [comment]
Github lets you upload and host artifacts outside your repo. You should not be checking in build artifacts, ever.

**Comment by ducin** [comment]
@DanielJoyce we support [bower](http://bower.io, which relies heavily on git. Currently we've been just pushing our product files into a commit, created an annotated tag - and bower used it for its versioning. We also support cdn.js, which uses a node.js post release hook.

I want to [entirely remove the dist directory from the git history](http://stackoverflow.com/a/17824718/769384) to make the repo a lot smaller. How should we move on now in your opinion? Can you suggest or recommend an approach?

**Comment by pateketrueke** [comment]
FTR; For `v0.5.x` I want to remove faker, chance, etc. from our bundles or they'll get bigger soon...

> The only dependencies that are fine to include are `json-schema-ref-parser` and `randexp`.

1. I mean, is not cool [having issues](https://github.com/json-schema-faker/json-schema-faker/issues/233) just by having bundled the wrong version.
2. Even worst this lead to [hacking around](https://github.com/apigee-127/sway/commit/7670613d8a9f29c43434084d3bb91bf86931af4d#diff-b9e12334e9eafd8341a6107dd98510c9R69) the generated bundle, when it should be easy to do.

This will change everything:

- The "locale" support has no sense since is a Faker feature, also [it can be achieved easily](https://github.com/json-schema-faker/json-schema-faker/blob/master/build/.locale.js#L4) (?)
- The website should provide some kind of support for extending the `jsf` instance on the fly (just like jsfiddle does for including files from CDN)
- The user is now responsible for loading the appropriate dependency if its needed (see #236)

Probably we may want to `console.log` some kind of warning if any given schema has keyword dependencies?

The thing is: working on this repository is freezing my computer! 🎉

**Comment by pateketrueke** [comment]
Seems to be fixed on all RC-series, the `v0.4.x` branch still slugish but it will be deprecated soon!
