### ISSUE TITLE
Missing optional field during generation

### ISSUE THREAD

**Issue by lcotonea** [json-schema-faker/json-schema-faker#152]
Test case: When a schema contains only one optional field, this field will never exist in generated JSON.
However, if there are two optional fields, then they are sometimes generated (that is good).

Here 2 failed test case:
- http://json-schema-faker.js.org/#gist/959c7af27f541c9dc4cfadf84bc4ddfd -> job is never generated
- http://json-schema-faker.js.org/#gist/5a056af465def2ab639a19c95ff855f2 -> description is never generated

Here a working test case (with two optional fields):
- http://json-schema-faker.js.org/#gist/881ac1dbdaba9815a2f81f79b31412d5

**Comment by ducin** [comment]
Hello @lcotonea, you were perfectly right, there was a bug. I have updated your comment and replaced the URI with permalinks (now we support them in the online demo page).
Since `v0.3.6` (released yesterday) this bug is fixed, please either download new version or try the online demo (hit multiple times ona single item - or wrap the item with an array).

**Comment by pateketrueke** [comment]
Sorry for the inconveniences, this issue is now solved on `develop`.

I'm closing this in order to release soon! :beers:
