### ISSUE TITLE
Max length is not respected for a lorem.sentence string

### ISSUE THREAD

**Issue by lcotonea** [json-schema-faker/json-schema-faker#153]
Max length is not taked into account when generating a lorem sentences string

Sample test :
http://json-schema-faker.js.org/#%7B%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22description%22%3A%7B%22type%22%3A%22string%22%2C%22faker%22%3A%22lorem.sentences%22%2C%22minLength%22%3A10%2C%22maxLength%22%3A10%7D%7D%2C%22required%22%3A%5B%22description%22%5D%7D

**Comment by ducin** [comment]
Thanks for submitting this one, @lcotonea. Actually, this is a tricky one. So far, JSF supports generating either faker/chance-based values (e.g. `"faker": "lorem.sentences"`) or pure-json-schema-based values (e.g. `"minLength": 10, "maxLength": 10`). Of course we can add that cross-type behavior, but we need to think about it first - how is it gonna work in terms of **all generators**, not just `faker.lorem.sentences`?

Currently, we check if either `faker` or `chance` property is present. If yes - go and use `external` module. Otherwise, use `string` module. In a certain order, so if `faker` was found then `string` was not executed (because of this order).

We'd need to keep the order, but execute `faker` first and then `string`. Or we may just leave things as they are - and let use either one or another, but not both. What do you think, @pateketrueke?

**Comment by pateketrueke** [comment]
I think we can apply those constraints on the generated values, at least for string values.

But there are lots of generators, and they can fit or not the json-schema constraints, so there is not guarantee that this will work on all cases.

I'll work on a general solution for this on the next version. 👍
