### ISSUE TITLE
jsf generating a collection of items instead of one item

### ISSUE THREAD

**Issue by atian25** [json-schema-faker/json-schema-faker#170]
we use `json scheme` to validate server response and mock before backend is done.

when use as mock data,  we want the array mock data return 100+ , but when use as validate,   `minItem` is not required.

that's to say, we want to controll array length without setting minItem in scheme

**Comment by ducin** [comment]
Hello @atian25, thanks for your issue submission, but please stick to the contribution guidelines:
```
If you're submitting a bug, please clearly state what is:

1. the JSON Schema content that fails - preferably using http://json-schema-faker.js.org/ (paste the schema, click `generate` and grab updated browser address bar URL
2. the result you get
3. the result you expected
```

**Comment by ducin** [comment]
@atian25 can you reply and provide more info?

**Comment by atian25** [comment]
HI, sorry for delay.

It's not bug, just usage feature request.

we use `JSON Scheme` for 2 purpose:
- when starting develop, just `json-schema-faker` to load scheme define to mock response data
- when  the backend is ready (they are java), then we don't need mock, but use scheme as validate rule to backend response.

then trouble is:
- when scene 1,  we usually need to mock more array data, so that in front-end we can test paginate
- when scene 2, the array minItem is not a  business rule, so we need to remove it.

so the feature request is:
- support some rule, such as `faker_minItem: 30`
- so we can got 30 array item in scene 1, and validate will not fail at scene 2

**Comment by ducin** [comment]
@atian25 I think I understand your concern very well.
ad 2 - minItems should not be there, since it's not a part of the schema anyway. So you're right there
ad 1 - can you tell me how are you using `JSON-Schema-Faker`? Is it some kind of a node.js server (meteor, express, whatever) or is it browser based? Anyway, there are 3 solutions I can think of:
* if you're using plain javascript code, instead of:

```
var item = jsf(schema);
```
simply use:
```
var collection = [];
for (var i = 0; i < NUMBER; i++) {
  collection.push(jsf(schema));
}
```

* take a look at [grunt-jsonschema-faker](https://github.com/json-schema-faker/grunt-jsonschema-faker#size) - it supports exactly what you need (`size`)

* we might think of introducing something like `jsf.collection(schema)` that would create an array of items of a given schema. But it would just be an alias for above for-loop. Would that make a big difference for you?

**Comment by pateketrueke** [comment]
@ducin you're absolutely right on `ad 2` buddy.

On `ad 1`, lets say the schema is:

```json
{
  "type": "object",
  "properties": {
    "results": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 100
    }
  },
  "required": ["results"]
}
```

@atian25 

1) I understand you are paginating something, so you need a mocked list with items
2) On your backend you are reusing the schema (which is very cool) to validate your response, but...

you cannot ensure to always having items (declared by `minItems`) on the back-end, but for mock/test'ing purposes is certainly desired, right?

> support some rule, such as faker_minItem: 30

Done.

Now, you can enforce `minItems` from jsf options:

```js
jsf.option({
  defaultMinItems: 100,
});
```

This way you're no longer tied to add/remove `minItems` from your schema for achieving both scenarios.

Once `develop` is merged and released, all this features should be available on all our jsf tooling.
