### ISSUE TITLE
external.js is using Function.prototype.apply improperly

### ISSUE THREAD

**Issue by SgtPooki** [json-schema-faker/json-schema-faker#171]
If you're submitting a bug, please clearly state what is:

#### the JSON Schema content that fails - preferably using http://json-schema-faker.js.org/ (paste the schema, click `generate` and grab updated browser address bar URL
```json
{
    "title": {
        "type": "string",
        "chance": {
            "pickone": ["one", "two", "three"]
        }
    }
}
```

#### the result you get
```
{
    "title": "o",
    "id": "http://json-schema.org/schema#"
}
```
#### the result you expected
```
{
    "title": "two",
    "id": "http://json-schema.org/schema#"
}
```

You can check out a quick test I wrote up here to show what's happening.

```
function foo(arr) {
    console.log(arr, arguments);
}

foo(["one", "two", "three"]);
foo.apply(this, ["one", "two", "three"]);
```
results in
```
[ 'one', 'two', 'three' ] { '0': [ 'one', 'two', 'three' ] }
one { '0': 'one', '1': 'two', '2': 'three' }
```

Why? Because we're applying the array to the function, which is splitting my single level array into three separate arguments, instead of one array argument.

So either we need to 
1. Provide a sample on json-schema-faker indicating that we may need to double wrap arrays (that is the easiest fix for this)
2. Remove lines 6-11 and 13-14 in external.js, leaving just the ```args.push(key[path])```
3. Something more clever or non-breaking that I have no insight into.

I did test the second option on my larger schema and everything else continued to work as expected. Was this code added to fix some previous issue, or as a precautionary fix for something expected?

**Comment by ducin** [comment]
Hello @SgtPooki, thanks for your bug submission. Actually, there is no bug :) yet, the usage was tricky and thanks for your deep insight, it took me a while before I solved that.

First of all, your schema seems to be invalid - it works with JSF, but you should define an `object` that has `properties`. And you don't define what it is. Perhaps some tools (like JSF) will carry on, but some might fail because of that. But that's just a comment.

Second, you are passing the generator arguments is a wrong way. When we do 
```
{
    "title": {
        "type": "string",
        "chance": {
            "pickone": ["one", "two", "three"]
        }
    }
}
```
you actually are calling `Chance.pickone("one", "two", "three")`. I.e., you call a function with 3 parameters. And this is NOT what you want. You want to call it with 1 param - array containing all above. So all you need is to wrap the 1,2,3 with  another square brackets, just as [the example here](http://json-schema-faker.js.org/#%7B%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22title%22%3A%7B%22type%22%3A%22string%22%2C%22chance%22%3A%7B%22pickone%22%3A%5B%5B%22one%22%2C%22two%22%2C%22three%22%5D%5D%7D%7D%7D%2C%22required%22%3A%5B%22title%22%5D%7D):
```
{
    "title": {
        "type": "string",
        "chance": {
            "pickone": [
                ["one", "two", "three"]
            ]
        }
    }
}
```

PS thx for your suggestions with fixing, I appreciate them, however, they would not work. Faker works differently and Chance work differently, hence, we can't remove code just because it'd fix a single case ;) The best you can do is to fork, try to modify the code and run tests (need nothing more than npm to do that). Then you'd see if a given change breaks anything. BTW, we're looking for contributors - R U interested?

**Comment by ducin** [comment]
I have added a new test to the suite. Additionally, I extended the docs, so that nobody have doubts about how JSF is working: https://github.com/json-schema-faker/json-schema-faker#user-content-advanced-usage-of-fakerjs-and-chancejs

Thanks @SgtPooki
