### ISSUE TITLE
"falsey" default values

### ISSUE THREAD

**Issue by AndreSteenveld** [json-schema-faker/json-schema-faker#181]
When generating data with a falsey default (```false```, ```""```, ```0```, ```null```) the default value is not respected.

I think [develop/lib/core/traverse.js#L29](https://github.com/json-schema-faker/json-schema-faker/blob/develop/lib/core/traverse.js#L29) is the cause of the bug and that it should actually read:

```
if (option('useDefaultValue') && 'default' in schema) {
```

I will make a pull request with some test cases tomorrow evening.

Example:
* [Reproduction](https://jsfiddle.net/pod3na0c/2/)
* Observed behaviour: Object with random values 
* Expected behaviour: An object that looks like this: ```{"string":"","number":0,"bool":false,"object":null}```

**Comment by ducin** [comment]
Thanks for the issue @AndreSteenveld, you are absolutely right.
Perhaps replacing `schema.default` with `schema.default !== undefined` would do the job. Looking forward to your PR :beers:

**Comment by AndreSteenveld** [comment]
Sorry for the delay, PR is #183

**Comment by ducin** [comment]
No worries @AndreSteenveld. Good job! The 3 languages is something we're not aiming at ;) We wanna get rid of javascript, which is a product of TS, but  we need to spend some time to reconfigure the build process. And coffeescript tests are because initially they were written in CS.

It'll be cool if you wish to contribute to `jsf` more! You're more than welcome to do so!

**Comment by ducin** [comment]
we've got some turbulence on develop (tough merge), so I moved your code directly to master. Will be released with upcoming release :-)
