### ISSUE TITLE
Support randexp.max as parameter from schema

### ISSUE THREAD

**Issue by spiffytech** [json-schema-faker/json-schema-faker#193]
`randexp` supports a property, `max`, which indicates how many repetitions will be generated for patterns like `+`, `*` or the unbounded `{1,}` pattern may have.

Please support reading this parameter from the schema for `string` types, in the same way faker and chance parameters are supported.

Also supporting this parameter for `patternProperties` keys would be great, but I'm not sure how to fit that into the JSON Schema syntax.

**Comment by pateketrueke** [comment]
I think we can use standard keywords from json-schema and then translate them to its related randexp/faker/change options.

Using `{ "type": "string", "pattern": ".+", "maxLength": 20 }` the value `20` should match the `max` setting.

It does make sense?

**Comment by spiffytech** [comment]
It's unclear to me from the JSON Schema spec, but I _think_ that syntax
would enforce string length even for patterned strings. So that would
introduce incorrect behavior.

For this reason, it's probably best to avoid standard keywords.

**Comment by pateketrueke** [comment]
You're right, mixing keywords is not the way...

Instead, adding support for that settings at schema-level (a) or compiler-level (b), or both?

a) can by anything that contains that rule, and also use the `pattern` keyword, e.g.

```json
{
  "type": "object",
  "properties": {
    "foo": {
      "type": "string",
      "pattern": ".+",
      "randexp": { "max": 20 }
    }
  }
}
```

b) can by an option within global jsf settings, e.g.

```js
jsf.option({
  defaultRandExpProperties: { max: 20 }
});
```

Of course we can support both styles, where the later will be applied as defaults, and let the former override as needed.

> I also had this issue before but I didn't take into account, just by refining the regexp my results were more precise... If the given pattern is too simple randexp will generate very large and strange values, weird.

What do you think?

**Comment by spiffytech** [comment]
I like the hash approach: it feels similar to the existing way to parameterize Faker and Chance, and it's clearly extensible if there are ever more parameters worth supporting.

I feel (a) provides all of the value this issue requests. (b) is strictly a convenience feature (since (a) can do everything (b) can), but my own use case doesn't need that convenience.

(b) may be worth supporting just for shipping a sane default with jsf?

**Comment by pateketrueke** [comment]
> may be worth supporting just for shipping a sane default with jsf?

Yes, the default (b) now is 10, which is a pretty basic limit.

I've discarded (a) for two main reasons:

- You are encouraged to understand JSON-Schema properly in order to exploit its capabilities
- JSF also is encouraged to understand JSON-Schema properly in order to exploit its capabilities

Adding an extra keyword just for setting up this max option is wrong.

The _JSON-Schema way_ shall be understand how apply min/max length constraints for all generated strings.

I've added a few basic specs for this:

```json
{ "type": "string", "pattern": ".+", "minLength": 21 }
{ "type": "string", "pattern": ".+", "maxLength": 2 }
```

If the max-default is 10, then:

- The first schema would have at least 21 chars.
- The second schema would have up to 2 chars.
- Otherwise any string generated would be between 0 and 10 chars.

Also I think it could be helpful having an option for changing this default on the fly, what do you think?

**Comment by pateketrueke** [comment]
Update: now it's possible to define the `max` through options:

```js
jsf.option({
  defaultRandExpMax: 3,
});
```

🎉
