### ISSUE TITLE
Feature request: Allow YAML in the demo input window

### ISSUE THREAD

**Issue by osher** [json-schema-faker/json-schema-faker#219]
Since YAML is a superset of JSON - replacing the parser engine should be easy.
Anything that works for JSON should work for Yaml, where Yaml is more readble.

This feature gets more important as more and more people write their open-api docs (fka swagger) in Yaml.

I understand the challenges are mostly integrating the parse-error notifications...?
If somebody could ninja this out - it will be super awsome!

**Edited:** add:
mm, I mean this demo
http://json-schema-faker.js.org/
I home I'm in the right place...

**Comment by ducin** [comment]
Hello @osher. Just to make sure... you want the online demo page to accept either JSON or YAML right? If so, then open an issue there: https://github.com/json-schema-faker/website-jsf
Otherwise it means you want to make `jsf` support YAML which, honestly, doesn't make any sense to me. NPM packages are composable, hence you can use e.g. [`yaml-to-json`](https://www.npmjs.com/package/yaml-to-json) like:

    jsf(yaml2json(yamlSchemaString))

more or less. That is beyond `jsf` responsibility.

**Comment by pateketrueke** [comment]
I think that adding this feature on the website would be easy and highly appreciated.

Also agree with @ducin, that is beyond `jsf` responsibility.

**Comment by osher** [comment]
yes, guys, you got me right.
I'll move it to website-jsf
thanks :)

**Comment by osher** [comment]
ah. it's already there... 😛  thanks 😸
