### ISSUE TITLE
All other constraints are ignored if enum is present

### ISSUE THREAD

**Issue by JonathanMontane** [json-schema-faker/json-schema-faker#224]
If the `enum` field is present, jsf will use any value from the enum, even if they don't respect the other constraints:

Example Error:
http://json-schema-faker.js.org/#gist/7547e5e627b35325b4a94ca73cea909e

Example of failing schema:
```json
{
  "type": "number",
  "enum": [1,2,3,4,5,6,7,8],
  "minimum": 3.5
}
```

What is expected:
```
any number in the list [4,5,6,7,8]
```

What is generated:
```
any number in the list [1,2,3,4,5,6,7,8]
```

How to probably fix it:
the check for enum is probably done way before the other constraints check, it should probably be moved to the same level as the other constraints.

**Comment by JonathanMontane** [comment]
It's unrelated, but I wanted to thank you for the amazing effort you did with respect to how `patternProperties`, `additionalProperties`, `required` and `min/maxProperties` should behave together.

**Comment by pateketrueke** [comment]
Why would you like to enumerate a value out of the range? 🤔

**Comment by JonathanMontane** [comment]
@pateketrueke, I suppose the argument here is "never trust user input". This also happens when we try to combine schemas to emulate OneOf, as it is not correctly supported at the moment. So, although the schemas we generated were correct per the JSON Schema spec, the generated object were not valid when there was an enum.

For instance,

```js
{
  "type": "integer",
  "enum": [ 1, 10, 100, 1000, 10000 ]
  "oneOf": [
    {  "maximum": 1000 }, // Schema A
    {  "minimum": 10 } // Schema B
}
```

can be translated into either:

```js
/* A && !B */
{
  "type": "integer",
  "enum": [ 1, 10, 100, 1000, 10000 ],
  "maximum": 10,
  "exclusiveMaximum": true
}
```

or

```js
/* !A && B */
{
  "type": "integer",
  "enum": [ 1, 10, 100, 1000, 10000 ],
  "minimum": 1000,
  "exclusiveMinimum": true
}
```

We naturally check all values of the enum, to see if they are complying with the rest of the spec, but we thought that this could be also fixed directly in JSF, as it's not super complicated to fix - it's a filter that validates the values from the enum against the underlying schema - and it would bring JSF one step closer to absolutely faithful to the JSON Schema spec.

**Comment by pateketrueke** [comment]
All my knowledge about json-schema rules comes from validating them first.

Using the service: http://www.jsonschemavalidator.net/

Your first schema is invalid for the value `100`:

```json
{
  "type": "integer",
  "enum": [ 1, 10, 100, 1000, 10000 ],
  "oneOf": [
    {  "maximum": 1000 },
    {  "minimum": 10 }
  ]
}
```

> JSON is valid against more than one schema from 'oneOf'. Valid schema indexes: 0, 1

Is interesting because `oneOf` should validate values only for one sub-schema defined, and no more. 

Switching from `oneOf` to `allOf` effectively works as expected.

Which value should be generated in order to validate?

Now, this schema is completely valid for the value `4`:

```json
{
  "type":  "number",
  "enum": [1, 2, 3, 4, 5, 6, 7, 8],
  "minimum": 3.5
}
```

Of course `2` is not a valid value...

I think this is a complicated topic, but simple schemas like above are easy to fix:

- We can try all values within the schema until one passes the constraints.
- If no one is found, then the schema cannot be faked.

If `jsf` can detect contradictory rules it should simple reject the whole value generation.

**Comment by JonathanMontane** [comment]
@pateketrueke yes, that process should work! (And it should actually work regardless of the complexity of the object)
