### ISSUE TITLE
Faked emails should use @example.com

### ISSUE THREAD

**Issue by convenient** [json-schema-faker/json-schema-faker#229]
Saw this pop up on reddit.com/r/programming, had a quick glance at it and the source code and saw the following.

It looks like this can generate "fake" data which could actually point to real email addresses owned by real people. This is corroborated in the sample here: http://json-schema-faker.js.org/#gist/89659ebf28be89d3f860c3f80cbffe4b

Where a few runs of the program give me output like
- "Martine.Stehr69@gmail.com"
- "Lawrence.Davis14@gmail.com"

All very convincing email addresses, ultimately I think it's a bit irresponsible to generate these emails for use in a test system in the event that an email event is actually triggered. This is exactly the use case for `@example.com`

http://www.iana.org/domains/reserved
>This domain is established to be used for illustrative examples in documents. You may use this domain in examples without prior coordination or asking for permission.

I'm not so sure how the code in your project works so I'm not submitting a PR yet, but a quick glance indicates that the following line and section is responsible for the rules defined when generating data. I think the following update would force email addresses to point to example.com.

https://github.com/Raynos/json-schema-faker/blob/master/lib/types/string.js#L14
```diff
   var regexps = {
-     email: '[a-zA-Z\\d][a-zA-Z\\d.-]{1,13}[a-zA-Z\\d]@{hostname}',
+     email: '[a-zA-Z\\d][a-zA-Z\\d.-]{1,13}[a-zA-Z\\d]@example.com',
      hostname: '[a-zA-Z]{1,33}\\.[a-z]{2,4}',
      ipv6: '[abcdef\\d]{4}(:[abcdef\\d]{4}){7}',
      uri: '[a-zA-Z\\d_][\\w\\\/\\d_-]{1,40}'
   };
```

**Comment by pateketrueke** [comment]
At this moment, `jsf` is only responsible for generating simple values like:

```json
{
  "type": "string",
  "format": "email"
}
```

The usage of `faker` (or `chance`, whatever) keyword is out of our responsibility, I think you can address this issue directly on the https://github.com/marak/Faker.js/ repository.

If you're interested please check the same issue with the other data-generators.

Thanks for your feedback! 👍

**Comment by ducin** [comment]
JSON Schema Faker is a tool that lets you generate domain-related data. You parametrize the data, but we don't support any limitations regarding law, ethics, etc. We give the tool, and the developers adapt it for their needs. Moreover, I can see no way to solve the issue you have described, since blocking "@abc.com" domain (or whatever other hardcoded thing) would make a lot more developers ask "why did you do that?" questions and I'd say they're right.
  
However, thank you for your input @convenient!

----

Going further to what @pateketrueke already wrote, you can use one out of two approaches to generate fake email addresses:

1. built-in `format`

```
{
  "type": "string",
  "format": "email"
}
```
will give you items like:
```
  "sikVq2IqL@IdPesgGMnVAEHAffQXUYpq.ako",
  "RLEfA4@XAHTshJFmTYXpEEvURcPXWCiWPXL.yhp",
  "7E3Il@tWiNOQ.rob",
```
[multiple items demo](http://json-schema-faker.js.org/#gist/39ad25b978c88100b5434e6ede904b19)

2. via vendor, [faker.js](https://github.com/marak/Faker.js/)

```
{
  "type": "string",
  "faker": "internet.email"
}
```
will give you items like:
```
  "Shanelle8@yahoo.com",
  "Brain.Altenwerth67@hotmail.com",
  "Natalie.Kassulke5@gmail.com",
```

[multiple items demo](http://json-schema-faker.js.org/#gist/f7c4cd06881ab6dc197e7c9ce1e6f538)

If you want to parametrise faker:internet.email, see [faker.js source code for more details](https://github.com/Marak/faker.js/blob/master/lib/internet.js#L24-L35)
