### ISSUE TITLE
What happened to a Faker date as ISOString?

### ISSUE THREAD

**Issue by ericsvendsen** [json-schema-faker/json-schema-faker#233]
Starting with v0.3.6, output from faker date methods is a Javascript date string, rather than an ISO string.  Why did this change?  Is it possible to get a faker date as an ISO string?

[Go here](http://json-schema-faker.js.org/#gist/1362757db7d216772c4b5ce4335799cf), and then change the version dropdown. 0.3.4 gives an ISO string, 0.3.5 gives an ISO string with extra escaped quotes, and 0.3.6 gives a Javascript date string.

**Comment by ducin** [comment]
@ericsvendsen confirm, you're right, diving into it...

**Comment by pateketrueke** [comment]
> Starting with v0.3.6, output from faker date methods is a Javascript date string, rather than an ISO string. Why did this change? Is it possible to get a faker date as an ISO string?

I think we cannot do much here, effectively the Faker's version could be the main problem here...

However you can override the `faker` dependency with the right version:

```js
// npm install faker@4.1.0 --save
jsf.extend('faker', () => require('faker'));
```

**Comment by jbesta** [comment]
I've also encountered this issue.

Here's simplified version of my JSON schema:

```
{
  "id": "event",
  "type": "object",
  "required": [
    "id",
    "start"
  ],
  "properties": {
    "id": {
      "type": "string",
      "faker": "random.uuid"
    },
    "start": {
      "type": "string",
      "faker": "date.past"
    }
  }
}
```

So I went through the code of `json-schema-faker` (`v0.5.0-rc3`) as well as `faker` library and here's what I've found:

`faker` returns instance of `Date` object from its date methods (`date.past`, `date.future`, `date.recent` etc.). `json-schema-faker` then takes this value and converts it to `String` (this happens inside method traverse using `utils.typecast` function). To quote:

```
function traverse(schema, path, resolve) {
  // ...
  if (typeof schema.generate === 'function') {
    return utils.typecast(schema.generate(), schema);
  }
  // ...
}
```
This conversion internally calls `toString` method of date object instead of desired `toISOString` method.

As a workaround, one could choose from 2 options:

1. define custom format:
```
jsf.format('pastDate', () => faker.date.past().toISOString());
```
Schema:
```
{
  "id": "event",
  "type": "object",
  "required": [
    "id",
    "start"
  ],
  "properties": {
    "id": {
      "type": "string",
      "faker": "random.uuid"
    },
    "start": {
      "type": "string",
      "format": "pastDate"
    }
  }
}
```
2. use `object` type in schema definition and handle coversion later.

Luckily, 2nd option was my choice since I'm using the code inside express application and I'm returning response as JSON from my endpoint using:
```
response.json(data);
```
which uses `JSON.stringify` that converts date to string using `toISOString`

**Comment by pateketrueke** [comment]
Thanks for diving into this @jbesta, what do you think about calling `toISOString()` if the generated data is a `Date` object?

I think this is related with #224 somehow... because we need to go further and ensure most constraints are being applied, and of course, implicit conversions are done as expected.

If `toISOString` is not desired as default, we can even add an option for handling it.

**Comment by jbesta** [comment]
@pateketrueke I agree, converting `Date`s to `String` via `toISOString` by default fits majority of use cases.
Custom conversion handler would handle the rest.
