### ISSUE TITLE
required: {Boolean} instead of required: {Array}

### ISSUE THREAD

**Issue by leibale** [json-schema-faker/json-schema-faker#237]
I try to use `required: {Boolean}` instead of `required: {Array}` in the schema and it's throws error.
```
Uncaught Error: (value.required || []).slice is not a function in /properties/obj/properties/prop1
    at run (json-schema-faker.js:503)
    at jsf (json-schema-faker.js:830)
    at app.js:923
    at Zr.<anonymous> (app.js:608)
    at bt (ractive.runtime.min.js:formatted:571)
    at yt (ractive.runtime.min.js:formatted:553)
    at vt (ractive.runtime.min.js:formatted:541)
    at ou.fire (ractive.runtime.min.js:formatted:6296)
    at HTMLButtonElement.e.addEventListener.handler (ractive.runtime.min.js:formatted:6142)
```
[example](http://json-schema-faker.js.org/#gist/2c8291d1191fedb65848088f1660397b). click on generate 2-3 times and i will see the error.

You can see in [jsonscheam code](https://github.com/tdegrunt/jsonschema/blob/master/lib/attribute.js#L478) that `required: {Boolean}` is supported.

**Comment by u982744** [comment]
I don't think you are defining your schema correctly. My understanding is that "required" property in a schema should be a sibling to "properties" property. Required is an array because it lists which properties are required.

Also the latest json schema docs say only use as array so best to stick with that.
http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.15

**Comment by leibale** [comment]
Yes, you right. I thought that this is in the draft because it in jsonscheme code..
