### ISSUE TITLE
Create property with static value

### ISSUE THREAD

**Issue by jbprat** [json-schema-faker/json-schema-faker#298]
Hello, 

I am trying to generate a type property on an object, with a default value, I read the documentation and found nothing related to giving a fixed value to a property.

This is the code I'm putting in the test faker:
```
{
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "default": "testModule"
    },
    "name": {
      "type": "string",
      "faker": "name.findName"
    },
    "email": {
      "type": "string",
      "faker": "internet.email"
    }
  },
  "required": [
    "type",
    "name",
    "email"
  ]
}
```

The result I have:
```
{
  "type": "elit et aliqua",
  "name": "velit al",
  "email": "dolor ea in"
}
```

The result I would want:
```
{
  "type": "TestModule",
  "name": "velit al",
  "email": "dolor ea in"
}
```

Thanks for your help!

**Comment by pateketrueke** [comment]
Yeah, we haven't implemented the `default` keyword support because the main concern of jsf is faking data.

Anyway your use case is valid: we need support for default values.

I'm adding this to the current milestone, because so much stuff is related with having options and expecting diverse results.

Thanks for your feedback!

**Comment by pateketrueke** [comment]
Hi, just enable `useDefaultValue` to get `default` values.

```js
jsf.option({
  useDefaultValue: true,
});
```

It was implemented but not documented, sorry.
