### ISSUE TITLE
FEATURE: extending "format"

### ISSUE THREAD

**Issue by fireproofsocks** [json-schema-faker/json-schema-faker#310]
I'm wondering what your thoughts are for adding support for custom formats in addition to (or instead of) the support for the custom `faker` keyword.

In other words, if we have a schema  such as this:
```
{
   "type": "string",
   "format": "email"
}
```

That should be sufficient -- do we need to rely on `"faker": "internet.email"`?

Or, if we want the value to represent a person's name, why not do something like:
```
{
   "type": "string",
   "format": "person_name"
}
```
instead of `"faker": "name.findName"`

If I'm reading the JSON Schema spec correctly, validators should ignore any formats that they don't understand.  They should also ignore keywords that they don't understand, so this can work either way, but I'm curious to know your thoughts on it.  The OAS/Swagger definitions don't always support custom keywords (?) so they require the use of the `x-` prefix, but JSON Schema does not.

**Comment by pateketrueke** [comment]
Hey, thanks for sharing your thoughts too! 👍 

`jsf` already supports custom formats/keywords, and also has built-in support for some formats like `email` and such.

So this just works: http://json-schema-faker.js.org/#gist/3fcadedaf41731267d0eaec5f71affa8/0.4.3

Since `0.5.0-rc1` we dropped the built-in support for custom keywords like `faker` or `chance`.

Now, we need to register the external support first:

```js
jsf.extend('faker', () => require('faker'));
```

Also having [custom formats](https://github.com/json-schema-faker/json-schema-faker#custom-formats) is fully supported.

Adding a new format for `person_name` is quite simple:

```js
jsf.format('person_name', () => 'Joe');

console.log(jsf({
  type: 'string',
  format: 'person_name',
}));
```

--

IMO the generated value for the built-in `email` format is not human readable, but still is valid.

That's why eventually relying on external generators can result in a good thing, since faked values are in most cases human-friendly.

I think we can improve the built-in formats to produce more human friendly-values on cases like this, but on any case it won't be as flexible like faker, chance, etc.

**Comment by pateketrueke** [comment]
Hi again, thanks for your interest on this project.

I'm curious about you need of implementing the feature you mentioned on #312 

Can you expand on this?

**Comment by fireproofsocks** [comment]
Maybe some of this is already in the code (if so, sorry!), but here's what I would like to add:

1. documentation for all supported formats (e.g. `"format": "ipv6"` or `"format": "email"`), including all custom formats.  As a schema author, I want to know what is available to me and how to modify my schema so that json-schema-faker can generate realistic fake data.  Is there a wiki page or something that indexes all the available formats and/or data types?  Where should that be added?

2. add support for custom formats (something like what is described for `"semver"`, but including a full set of the data formats supported by https://www.npmjs.com/package/faker and perhaps a few more).  I'm not sure where to add something like that in the code.

As discussed, other JSON Schema validators should ignore keywords and formats that they don't recognize.  Although I would prefer to notate custom data formats using the "format" keyword (e.g. `{"type": "string", "format": "first_name"}`), others may prefer to use a custom keyword (e.g. `{"type": "string", "faker": "first_name"}`.  I'm not sure if you have any preference, but the code could probably support both options -- some schema authors may prefer one method over another.

Thanks for any feedback/input on this!

**Comment by pateketrueke** [comment]
This is a great topic, let me answer your questions:

1. We added just a few [information and links](https://github.com/json-schema-faker/json-schema-faker#supported-keywords) on the README.md file but...

The README _should_ have that information but actually is becoming larger and difficult to read and search. I was thinking on a more structured website, or using the wiki, anything that can help us to simplify the information for our users like you.
  
It would be awesome if we're able to renew the project's website for the next stable release too.

Even something like a json-schema-ipsum could work too, or just a table with all posible formats both built-in and external, idk.

Do you have something in mind?

2. What do you think on `{ "format": "faker.first_name" }` as equivalent for `{ "faker": "first_name" }` ?

This allow us to reuse the built-in support for custom keywords, but this time, for dynamic formats.

Personally I don't have any preference between `format` or any other keyword as long the schema remains valid and reusable.

But yeah, I liked the idea, because `format` is a standard keyword and makes all sense.

Supporting both styles is a MUST since we can't always rely on that `format` will be ignored. 👍

**Comment by fireproofsocks** [comment]
Great news re the README!  Maybe a dedicated page in the Wiki might be an easy place to keep track of that data?  Or even a dedicated .md file in the repo somewhere -- it's not so important where the file is, it just needs to be someplace where users can find it and see what formats are available.

Format names like "faker.first_name" etc. would of course work fine, however I think it would probably be better to **not** use the "faker." prefix.  Here's are a couple reasons why:

1. The format itself isn't fake.  It's a _real_ format.  So, in a way, the prefix is confusing.
2. Other validators (e.g. custom validators) might support other formats, and they would not name the formats with a "faker." prefix (again, because the formats are real).
3. Schema authors are first and foremost describing their _data_.  The faker functionality of the `json-schema-faker` package (or any other package) is secondary to their data.  It's conceivable that a schema author would name their formats without ever needing to generate fake data, so I think that should be supported as much as possible.

So I think it would be best to use names that described the _formats_, not the _generators_.  So the name (IMO) should not be dependent on anything in the faker library.  At least, that was my line of reasoning when I wrote the PHP `jenerator/jenerator` package: https://github.com/fireproofsocks/jenerator -- I listed out the formats supported there from the PHP faker package.

Of course, it's possible to support both options, e.g. "first_name" and "faker.first_name" might call the exact same generator.  What do you think?

**Comment by pateketrueke** [comment]
> use names that described the **formats**, not the generators

Bingo!

Now I got what you meant, yeah it would be very helpful to build a list of _extended_ formats regardless the generator: that way the schema would be more reusable across languages, etc.

The question here is, how can we approach that? Because it's very possible that many formats will be dependant of external generators or fakers.

I don't want to declare external generators as dependencies again, so how we can enable this feature without bloating the package?

Even I think this can be another module aswell, just containing extended formats and its dependencies for them. And once done, we can just plug-in that on JSF with `require('jsf-extended-formats')(jsf);` what do you think?

**Comment by fireproofsocks** [comment]
Sure, it could be a separate package -- I think that's probably up to you and how you would like to organize things.  As long as the solution is flexible and well documented, I don't think users would have an issue with it one way or another (?), but as a developer maybe it does?  It's up to you I think.

**Comment by pateketrueke** [comment]
After thinking a while I realised this is not an issue.

JSF concerns are very limited, and thanks its extensibility, providing extra functionality (that can be built on top of it) is currently out of the scope.

TBH I like the idea of having lots of standarized formats that schema-authors can use, but is not up to me doing that work (unless I needed the same).

I'll keep this issue open until we got a module providing this support, of course any PR related with documentation is also worth, mentioning the resulting module shall be a MUST.

So much thanks for your feedback, I really appreciate your interest on this project.

PS: kudos for `jenerator` -- the idea of porting JSF to PHP (I feel comfortable with it) has been around on my mind for a while, I always wanted to see more generators like this in more languages; also I guess a great improvement could be having a way of sharing custom formats on an intermediate format, YAML, JSON, whatever... 🍻 

(sorry for my _english_)
