### ISSUE TITLE
backward compatibility for version 0.5.0-rc1

### ISSUE THREAD

**Issue by sundeep95** [json-schema-faker/json-schema-faker#329]
Redfish schemas are compatible with version 0.5.0-rc1. But the repository in the github is the latest version.
How can I get the previous required repository to work on my project.

Thanks
Sundeep

**Comment by pateketrueke** [comment]
You can stick to a fixed version of this library, just try: `npm install json-schema-faker@0.5.0-rc1`

BTW, do you have a working schema (from redfish) just to understand?

**Comment by sundeep95** [comment]
Hi
I installed the json faker schema version 0.5.0-rc1 by using above stated command.
When I give the json schema as input in this site http://json-schema-faker.js.org/ the json output was coming with fake data. (required)
But when I use the same schema and tried with github repository terminal commands in ubuntu it was showing following errors:

Error: Unsupported schema version (v4 only)
    at Object.module.exports [as normalizeSchema] (/home/sundeep/Desktop/demo/node_modules/deref/lib/util/normalize-schema.js:53:11)
    at /home/sundeep/Desktop/demo/node_modules/deref/lib/index.js:59:18
    at Array.forEach (native)
    at $ref (/home/sundeep/Desktop/demo/node_modules/deref/lib/index.js:58:35)
    at generate (/home/sundeep/Desktop/demo/node_modules/json-schema-faker/lib/jsf.js:19:21)
    at Object.<anonymous> (/home/sundeep/Desktop/demo/run.js:4:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

What is the problem?
How can we run the same schema in github with version 0.5.0-rc1 to get fake json data from json schema?

--Thanks

**Comment by pateketrueke** [comment]
Thanks for the details, I'm looking into it and seems that the schema is well defined, but somehow remote references are not being resolved. Let me see what can I do to solve this issue.

**Comment by sundeepkumargorantla** [comment]
Can issue be resolved?
Possible to get same output that we get through online site  http://json-schema-faker.js.org/ in the ubuntu implementation for the version 0.5.0-rc1?

--thanks

**Comment by pateketrueke** [comment]
> Can issue be resolved?

Not yet, sorry.

I tried your schema on the online editor but is not working yet...

We are using [json-schema-ref-parser](https://github.com/BigstickCarpet/json-schema-ref-parser) in order to resolve all remote references, it would be helpful if you can resolve your schema with this library just to see if it works as expected.

TBH; the schema is totally valid, I just tested on http://www.jsonschemavalidator.net/ and no problems there, so the problem could be the library we're using, or something related with references, I need more time to investigate.

Sorry if this can't be done asap, I'm doing this in my spare time, for free.

**Comment by sundeepkumargorantla** [comment]
Hi Sir
Thanks a lot fro your effort.
The good part is the schema is working on online editor. Its not working with github code in linux. It says above mentioned errors.
Here I attach the output I got for the schema using online editor.
But another issue it displays only the properties which has required property as true, otherwise it may or may not display in the fake json data output.
<img width="803" alt="capture" src="https://user-images.githubusercontent.com/29860648/31422720-485bcee2-ae6d-11e7-8c4a-c0526fe6961d.PNG">
)
--Thanks

**Comment by pateketrueke** [comment]
Yeah, there's something on the RC1 which somehow is working... 🤔

**Comment by pateketrueke** [comment]
Fixed now under development, thanks for your feedback!
