### ISSUE TITLE
Use existing data to generate the "schema-faker"

### ISSUE THREAD

**Issue by dsmrs** [json-schema-faker/json-schema-faker#340]
I'm working on a project that has no test at all (really bad 😱), and I would love to generate automatically some schema-faker from existing data in the DB instead of writing them down. The idea here is "scan" an actual JSON (in a file or via an API) and generate the schema-faker from it using regexp.

I started a repo [>> :octocat: dsmrs/json-to-jsf :octocat: <<](https://github.com/dsmrs/json-to-jsf) 

for now it will only do this: (I use the lib validator.js to guess the format of the data).

```bash
# path/of/existing.json
# {
#   id: 3,
#   firstName: "John"
# }
node index.js <path/of/existing.json> <suffix>
# will generate a file named: <existing>-<suffix>.json
# {
#   type: "object",
#   properties: {
#     id: {
#       type: "integer",
#        faker: "random.number"
#     },
#     firstName: {
#       type: "string",
#       faker: "name.firstName"
#     }
#   }
# }
```

I'm actually quite a bad developer, this small cli/lib could do much more (call an array of api routes, make a converter online, etc.). If you think it usefull please come help! 😄

**Comment by pateketrueke** [comment]
Hi, I think this is very useful, because many people only have json samples, and convert them to json-schema is quite difficult without understanding.

As note, json-schema-faker does not rely only on `faker` so any other external generator is allowed too, so constraning your solution only to `faker` keywords will not scale if you want to support more later.

The first step I would do is trying to use something existent, e.g. [json-to-json-schema](https://www.npmjs.com/package/json-to-json-schema) in order to convert the most common objects.

Of course, I like the idea of guessing a faker-type (lets call it x-type) or built-in-type based on the value, that's very helpful. So any pre/post processing is worthy if you can use keywords from any generator or built-in types.

**Comment by dsmrs** [comment]
thanks for the *json-to-json-schema* ...didn't search enough. Yes could be a good start, and then let people choose how to generate their data (from faker, regex, enum, ...). If I find some free time next week, I'll have a look at it.

Maybe design a function that links common keys (like `first_name`, `phone`, `email`, `address`, ...) to faker formula and let the possibility to use it or no. Also let the people make their own "key-link" or override existing one.

**Comment by ilyazub** [comment]
@dsmrs There is such module: https://github.com/nijikokun/generate-schema

**Comment by dsmrs** [comment]
Yes, thanks @ilyazub but it's not actually what I imagined. This only generate a normal json-schema with types. What I imagine is to have an input with "faker keyword type" base on the input data (key or value).

if I give 
```JSON
{
  firstName: "Dorian",
  phone: "+32477838291"
}
```
your generator will only give me the type of the entries (both `string`), but I can't really fake them... what I want is to be able, with regex/keys, give the corresponding json-schema-faker:

```
{
  type: "object",
  properties: {
    firstName: {
      type: "string",
      faker: "name.firstName"
    },
    phone: {
       type: "string",
       faker: "phone.phoneNumber"
    }
  }
}
```

**Comment by kristianmandrup** [comment]
We are working on something similar here:

https://github.com/yeay-tv/fake-rest-api

You might find it useful ;) Still very WIP but gets us most of the way already

**Comment by pateketrueke** [comment]
I think this could be moved somewhere into docs. 🤔
