### ISSUE TITLE
Feature Request: format: "date"

### ISSUE THREAD

**Issue by MrChoclate** [json-schema-faker/json-schema-faker#358]
You support `format: "date-time"`, can you support the format "date" please?

**Comment by pateketrueke** [comment]
The format `date` is from which json-schema version?

We support only the draft for the v4 version, and therefore such format is not listed there.

Of course, this is not a problem itself because [you can extend `json-schema-faker`](https://github.com/json-schema-faker/json-schema-faker#custom-formats) to achieve that:

```js
jsf.format('date', () => {
  // return a random date-value
});
```

**Comment by MrChoclate** [comment]
You are right. It seems to be restored from draft 3 in draft 7 (
http://json-schema.org/draft-07/json-schema-release-notes.html#formats).
The link in your Readme sent me to the latest draft.

Do you plan to support it in the future or should I close this issue?

**Comment by pateketrueke** [comment]
> The link in your Readme sent me to the latest draft.

Oh, I think the link it's bad, I'll fix this asap.

> Do you plan to support it in the future or should I close this issue?

Yeah, we would like to support the next drafts, so I think it will happen on time.

For now, since formats are not difficult to implement you can add that support as I commented before.

If you can do that, I think we can include your work in a PR soon. 🍻 

Thanks for your feedback!

**Comment by penx** [comment]
[sway](https://github.com/apigee-127/sway) uses json-schema-faker in order to return mocks for OpenAPI/Swagger specifications.

OpenAPI/Swagger has data types listed here:

https://swagger.io/specification/#dataTypes

Including `type: "string", format: "date"`.

I guess there are minor differences between OpenAPI JSON Schema which I expect extend to type definitions, so json-schema-faker wouldn't be designed to be 100% compatible with OpenAPI spec.

If that's the case, it would be good to have a way to be able to pass in configuration options that extend json-schema-faker to add support additional formats, so that it could be configured to be 100% OpenAPI compatible.

**Comment by pateketrueke** [comment]
Released on RC13, thanks for your effort! 🎉
