### ISSUE TITLE
Incorrect data type

### ISSUE THREAD

**Issue by clinyong** [json-schema-faker/json-schema-faker#364]
With below schema

```json
{
    "type": "object",
    "properties": {
        "channelIDs": { "pattern": "^\\d+$", "type": "array", "items": { "type": "string" } }
    },
    "required": ["channelIDs"],
    "$schema": "http://json-schema.org/draft-04/schema#"
}
```

The result I got

```json
{
  "channelIDs": "0086011776"
}
```

The result I expected

```json
{
  "channelIDs": ["0086011776"]
}
```

The reproduce link 

<http://json-schema-faker.js.org/#gist/0ae68962ce5ae6ce54e766514b42f743/0.5.0-rc11>

**Comment by pateketrueke** [comment]
The `pattern` attribute should be placed within `items` in order to _shape_ each item value.

I mean, the `pattern` attribute is exclusively for `string` usage.

`json-schema-faker` will try to infer some types based on known attributes, in your case `pattern` was forcing the whole schema to be treated as `string` and not as `array` as you expected.

**Comment by pateketrueke** [comment]
Closed, see: http://json-schema-faker.js.org/#gist/7b71604a0215208bf82fe4d2f8105f33/0.5.0-rc12
