### ISSUE TITLE
How do you increase the number of items when using Chance JS?

### ISSUE THREAD

**Issue by rodoabad** [json-schema-faker/json-schema-faker#451]
Just a general question. How do you increase or set the number of items generated by Chance JS if it's an array?

**Comment by pateketrueke** [comment]
Hi @rodoabad, can you provide an example?

I mean, you can use `minItems` to declared how many items you expect to be generated.

Otherwise it will be a random value, probably 5 or below.

Beyond that `jsf` can't do anything else, if you're using the `chance` generator _chances_ are you want to provide additional options to it, e.g.

```json
"chance": {
  "email": {
    "domain": "fake.com"
  }
}
```

**Comment by rodoabad** [comment]
```
    "locations": {
      "type": "array",
      "items" : {
        "$ref": "./location.json"
      }
    }
```

Will I be also able to use `x-chance` here?

**Comment by rodoabad** [comment]
I used `minItems` and `maxItems` successfully.

**Comment by pateketrueke** [comment]
That's it, you can use any generator without any depth issues.

Glad that `min/maxItems` helped you. 🍻

**Comment by rodoabad** [comment]
Yep! Thanks, @pateketrueke
