### ISSUE TITLE
anyOf not working correctly with enum conditional

### ISSUE THREAD

**Issue by acuster77** [json-schema-faker/json-schema-faker#479]
Schema
```javascript
{
  "type": "object",
  "properties": {
    "foo": { "enum": ["bar", "baz"] },
    "bar": { "type": "string" },
    "baz": { "type": "string" }
  },
  "required": ["foo"],
  "anyOf": [
    {
      "properties": {
        "foo": { "enum": ["bar"] }
      },
      "required": ["bar"]
    },
    {
      "properties": {
        "foo": { "enum": ["baz"] }
      },
      "required": ["baz"]
    }
  ]
}
```
Expected to have one of two outcomes 100% of the time:
```javascript
{
  "foo": "baz",
  "baz": "lorem ipsum"
}

OR 

{
  "foo": "bar",
  "bar": "lorem ipsum"
}
```
Sometimes returned on generation
```javascript
{
  "foo": "bar",
  "baz": "lorem ipsum"
}

OR

{
  "foo": "baz",
  "bar": "lorem ipsum"
}
```

Using the webtool: http://json-schema-faker.js.org/

**Comment by pateketrueke** [comment]
This case is very specific, therefore is bit ambiguous to resolve properly.

Let me explain you:

Each time `jsf` sees a `anyOf/oneOf` reference it will pick none or one, depending of the keyword, and `random.pick()` is used; then, the obtained sub schema is merged on the current schema.

> Here are heuristics that are enough clear to validators, but for generators there are not rules given yet. If validation rules are too specific and precise it's probably that `jsf` will not be able to generate anything, but also without rules the results might not look as you wanted in a first sight.

The strategy we're applying for arrays is just merging while keeping unique values only, instead of replacing whole arrays.

So `jsf` thinks:

- `"required": ["foo"]`  + `"required": ["bar"]`  = `"required": ["foo", "bar"]` 👍 
- `"enum": ["bar", "baz"]`  + `"enum": ["bar"]`  = `"enum": ["bar", "baz"]` 🤔 ?

> That's why you get unmatched values for `foo` and `bar` as you expect. Can we do it better?

a) A workaround for this is just avoiding the `foo` property on the root schema, while keeping it on the `anyOf` sub schemas. That should give you positive results.

```json
{
  "type": "object",
  "properties": {
    "bar": { "type": "string" },
    "baz": { "type": "string" }
  },
  "required": ["foo"],
  "anyOf": [
    {
      "properties": {
        "foo": { "enum": ["bar"] }
      },
      "required": ["bar"]
    },
    {
      "properties": {
        "foo": { "enum": ["baz"] }
      },
      "required": ["baz"]
    }
  ]
}
```

IMO this is better and clear than having duplicated details on the same schema, but it's up to you.

However be aware of the merging strategy described above, if you think something can be refined we're open to listen your suggestions.

b) Also I think this can be _probably achieved_ using `dependencies` to disambiguate, but that's even more complicated to achieve because it involves validating the generated schemas, etc.

> The current behavior for this will not change until we get enough quorum to define how it should works for everyone.

So much thanks for your feedback!

**Comment by acuster77** [comment]
@pateketrueke 
Thanks so much for the excellent explanation. 
> IMO this is better and clear than having duplicated details on the same schema, but it's up to you.

Agreed.  My use case of `anyOf` is simply a workaround for not having "if/else" logic available with JSF yet. I'm fine with closing this if you are 👍

**Comment by pateketrueke** [comment]
Thank you!

Regarding `if/then/else` it's really a beautiful feature, but since it implies additional validations I think It won't be included as built-in. I'm considering possible solutions using the existing APIs for custom keywords and generators, probably we can solve advanced features through them and any third-party validator. 🍻
