### ISSUE TITLE
JSON schema faker is not respecting description of the properties

### ISSUE THREAD

**Issue by Dhroov7** [json-schema-faker/json-schema-faker#533]
**Descriptions are getting removed by json-schema-faker**

1. Schema-
`{
				"properties": {
					"id": {
						"type": "integer",
            "format": "int64",
            "description": "This is a description"
					}
				}
			}`
2. Result - 
`
{
  "id": -70286268
}
`
3. The result i expected-
`
{
  "id": -70286268,
"description":  "This is a description"
}
`

**Comment by Dhroov7** [comment]
@pateketrueke Please take a look at this.

**Comment by pateketrueke** [comment]
I did not get you, is not longer an issue then? 🤔

**Comment by Dhroov7** [comment]
@pateketrueke No, actually I researched and got to know that JSON schema faker can't have two keys of a single property. What do you say?

**Comment by pateketrueke** [comment]
I think those properties does not affect how data is being validated, and because of that they don't need to be preserved after data generation.

Why? The concept behind "json-schema _faking_" is being able to produce a value that _can be_ validated through the original schema.

Adding that description back to the generated object will break our schema.
