### ISSUE TITLE
Is there current Documentation on how to use JSONPath to generate related sets?

### ISSUE THREAD

**Issue by toddgeist** [json-schema-faker/json-schema-faker#546]
I can't seem to find anything current on how to use JSONpath to generate related data sets.

I can see from the source here - https://github.com/json-schema-faker/json-schema-faker/blob/6c728d048e107092161921c46fa2d79b637ce30d/src/core/run.js#L32

that a random key is picked from an array.  But I am not sure about `cycle`, `reverse`, and `count` are supposed to work

any clues?

**Comment by pateketrueke** [comment]
Sure, first we need to know that JSONPath will work only on already generated results, e.g.

```json
{
  "type": "object",
  "properties": {
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 0,
            "maximum": 10
          }
        },
        "required": ["id"]
      }
    },
    "randomItem": {
      "jsonPath": "$..items[*].id"
    }
  },
  "required": ["items", "randomItem"]
}
```

Given that, `items` will be an array of objects and `randomItem` will be any ID from such list, e.g.

```json
{
  "items": [
    {
      "id": 0
    },
    {
      "id": 7
    },
    {
      "id": 6
    }
  ],
  "randomItem": 7
}
```

I'm using https://jsonpath.com/ to validate such expression before passing them to jsf, the key is always have a valid document, and then just extract such data with jsonPath expressions.

> We don't support cross-references for jsonPath yet, but that can be added later, e.g. `OtherSchema.json#$..items[*].id` (not sure if you need/want such feature, or if it's enough valid)

**Comment by toddgeist** [comment]
I got around the Other Schema issues by putting all schemas in `definitions`.  this seems to work just fine.

but what do the `count` `cycle` and `reverse` options do?

**Comment by pateketrueke** [comment]
> but what do the count cycle and reverse options do?

There's another way to use `jsonPath`, e.g.

```json
{
  "jsonPath": {
    "path": "$..items[*].id",
    "group": "blog_items",
    "cycle": false,
    "reverse": false,
    "count": 1
  }
}
```

Internally, the `group` value is used to keep an index, in case the `path` is repeated on the same schema this would help to avoid collisions.

The `cycle` and `reverse` options are used together, lets say you produce a list of 10 items, then you can cycle them in order, or in reverse-order. So that give you ordered results from a pre-calculated jsonPath expression.

Finally `count` is the amount of items you expect to extract from the results, and they'll be used as dispatched values when resolving paths, etc.
