### ISSUE TITLE
Using Min/MaxLength when defined in the options but not in the schema

### ISSUE THREAD

**Issue by saad-kh** [json-schema-faker/json-schema-faker#547]
Hi 

By looking at [this line of code](https://github.com/json-schema-faker/json-schema-faker/blob/4c0a3e15999222859d14e4ee1c3b62bffc08a9cf/src/core/utils.js#L97) I understand that if no ```minLength``` or ```maxLength``` are set in the schema, we don't get to use the ones defined in the options because ```if (_maxLength && params.maxLength > _maxLength)``` will always be false in this case.

Is this a normal behavior? I would expect the ```maxLength``` set by the options to be used even when we do not have one set in the schema.

**Comment by pateketrueke** [comment]
Got you, as I remember such options are used to avoid excessive input from user (who wrote the schema, in case you're not the author) because they can say `"maxLength": 10000000000` and is not very suitable.

So, when you set `jsf.option({ maxLength: 1000 })` you are saying that user schemas will never reach such limit, if the used schema has no maxLength then is just ignored.

That was the reason behind most options, but I see now that you also want to use them as defaults, not as overrides (if present) right?

**Comment by saad-kh** [comment]
Yes, exactly.

My issue is that I have a jsonSchema with a lot of required string properties, but when `minLength` is 0 (as by default), some strings are generated with empty string values `'"'`, this breaks validation afterward. 

I would love to be able to tell that empty strings cannot be generated for required properties, either by specifying a `minLength` or having the module be aware of this issue.

**Comment by pateketrueke** [comment]
Yeah, totally agree, I think the way to go is making all these options also as defaults.

Do you mind on opening a PR for or do you prefer to wait a bit more?

**Comment by saad-kh** [comment]
I won't mind opening a PR, but I'll limit it to the `minLength` and `maxLength` options, will that be alright with you?

**Comment by pateketrueke** [comment]
Yeah, feel free to fix minLength/maxLength only, every little help counts!

**Comment by saad-kh** [comment]
PR #548 opened to fix this issue.

**Comment by saad-kh** [comment]
PR merged, issue should be solved with next release

**Comment by zgababa** [comment]
Hey ! 
Thank you @saad-kh for this great work ! 
@pateketrueke When we will be the next release ?  We need this fix in our team :)

**Comment by pateketrueke** [comment]
RC24 released! 🎉
