### ISSUE TITLE
Infer type issues

### ISSUE THREAD

**Issue by pateketrueke** [json-schema-faker/json-schema-faker#62]
This schema is failing:

```json
{
  "id": "matches",
  "type": "object",
  "required": ["items"],
  "properties": {
    "items": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "maxItems": 10
    }
  }
}
```

Expected:

```json
{
    "items": [
        "accusamus eveniet veritatis dolores impedit", 
        "voluptatem eaque", 
        "hic perspiciatis sapiente", 
        "sed culpa eveniet", 
        "nihil a", 
        "quisquam vitae praesentium", 
        "fugit voluptas inventore sunt ut", 
        "sit accusamus omnis ducimus expedita"
    ]
}
```

Actual result:

```json
[
    [
        "odit et hic", 
        "possimus ex nobis amet", 
        "est unde sed", 
        "cum sequi ea itaque velit", 
        "consequuntur quia", 
        "quidem quasi nam", 
        "voluptas possimus iusto dolore", 
        "est ea quia", 
        "ea quisquam omnis mollitia"
    ], 
    [
        "quia incidunt", 
        "nesciunt", 
        "ut", 
        "at repellendus commodi", 
        "id quaerat laudantium quidem", 
        "modi expedita", 
        "dignissimos asperiores voluptatem nihil consequatur"
    ]
]
```

If I change the property name to anything else (but infer keywords) works properly.

if the inferred type is an object having a `type` keyword should stop inferring?

cc: @whitlockjc

**Comment by whitlockjc** [comment]
Interesting.  I thought about this at implementation time but I didn't have a good solution.  Let me give this some thought.

**Comment by whitlockjc** [comment]
Basically, we need to know if `items` is an attribute or the `items` portion of an `array` definition.

**Comment by whitlockjc** [comment]
This shouldn't be that hard to fix, I'll have a PR shortly.

**Comment by pateketrueke** [comment]
Basically `if (obj.items && typeof object.items.type === 'string') // not an array`

**Comment by whitlockjc** [comment]
I think it's bigger than that.  Any of the defining properties for each type, if you use that as a `properties` property, you can run into this issue.  It's not specific to arrays.

**Comment by whitlockjc** [comment]
But what's interesting is that json-schema-faker does not distinguish between *"user provided values"* and *"JSON Schema values"*.  What I mean by that is that json-schema-faker will attempt to find the type for the `properties` object for an object when it really shouldn't since it should always be an object.  So if I have a `properties` property on my object, I'd have something like this:

```js
{
  "type": "object",
  "properties": {
    "properties": {
      "additionalProperties": {
        "type": "string"
      }
    }
  }
}
```

json-schema-faker will try to find the type of `['properties']` and `['properties', 'properties']`.  How json-schema-faker currently works is for `['properties']` it expects `undefined` to be returned to basically **ignore** processing it.  That's great and all but how do you special case `['properties']` to return `undefined` while still allowing you to return `object` for `['properties', 'properties]` and to any level of nesting?  What seemed like a quick fix is likely not so.

**Comment by whitlockjc** [comment]
What appears to be happening is that `['properties']` is being checked for an invalid type since its type is not provided and when it sees an `items` property, it assumes an array.  Let me see if I can come up with something.

**Comment by whitlockjc** [comment]
I have something working and I'm writing a few extra tests.

**Comment by whitlockjc** [comment]
First pass is in PR #64.  The only way to reproduce this in testing and do a `type` test is for arrays but I did ensure that this worked for objects and other types as well.
