### ISSUE TITLE
Add unexpected fields in object

### ISSUE THREAD

**Issue by virginiadb** [json-schema-faker/json-schema-faker#686]
It will add unexpected fields such as "cupidatat57" in object.

**Comment by pateketrueke** [comment]
That's totally expected actually, that behaviour is enabled by default, disable it with:

```js
jsf.option('fillProperties', false);
```

**Comment by virginiadb** [comment]
> That's totally expected actually, that behaviour is enabled by default, disable it with:
> 
> ```js
> jsf.option('fillProperties', false);
> ```

It will miss some expected fields when I set false.
It will add some unexpected fields when I set true.
Now I am confused.
I need help.

**Comment by virginiadb** [comment]
It seems to be right when I retry it now.
I am totally confused.

**Comment by pateketrueke** [comment]
Well, this tool is designed to generate random results, i.e. if you don't have any `required` field then nothing guarantees your field is gonna be generated... because is not required, and hence it's considered as optional.

So, having an object definition with weak or none constraints would lead to random properties to be generated, not all the time.

If you want all the properties to be generated then enable them with `jsf.option('alwaysFakeOptionals', true);` and that should be enough.
