### ISSUE TITLE
A way to calculate all possible combinations of json based on a enum only json schema ?

### ISSUE THREAD

**Issue by floarc** [json-schema-faker/json-schema-faker#76]
Hello all,

Lets say i have a json schema made to describe a car.
And this json schema is only made of enum properties.
eg : 
color : red, blue ,white, yellow
motorisation : 100hp, 120 hp
and so on...

Is there a way to use json-schema-faker to generate all different jsons where each json representing a unique car ?

My idea behind this, is to be able to draw a kind of tree diagram of all possible car.

Could this feature be seen as json-schema-faker some kind of major improvement?

Any answer would be welcome !

Thx by advance!

**Comment by ducin** [comment]
Hi Florent,

No, currently there is no such feature. The thing is that jsf is used to generate independent samples. And what you need is a relation between the samples: uniqueness.

The problem is that we can't introduce a feature that would satisfy enums only. We do have dozens of other definitions, such as regexes. Imagine, how could we generate all possibilities of a regex like `[A-Za-z0-9]*`? I don't have an idea here, and the solution has to be generic.

WHat I'd recommend you is to write some js code, e.g. for inside a for that would generate an array of possibilities. Then generate a big json-schema definition and run jsf against it. So just generate jsf dynamically.
