### ISSUE TITLE
interpretation of oneOf

### ISSUE THREAD

**Issue by igorshmukler** [json-schema-faker/json-schema-faker#84]
Currently json-schema-faker interprets oneOf, much the same as anyOf. Intuitively, to me, oneOf implies one [and only one] item from the items list. While anyOf can be interpreted as some [none or more] and allOf would mean every item.
That's the way I understand these.

**Comment by pateketrueke** [comment]
I understand... so, we trying to make jsf compliant with the JSON-Schema standards.

Did you say that anyOf means 'none or more' and you know where is defined that constraint or it's only your point of view?

**Comment by pateketrueke** [comment]
Bye the way, I found this:

http://json-schema.org/latest/json-schema-validation.html#anchor85
> anyOf - An instance validates successfully against this keyword if it validates successfully against at least one schema defined by this keyword's value. 

http://json-schema.org/latest/json-schema-validation.html#anchor88
> oneOf - An instance validates successfully against this keyword if it validates successfully against exactly one schema defined by this keyword's value. 

Both references are for validation, but I think applies for generators in order to produce valid values.

**Comment by igorshmukler** [comment]
All for what you are saying. Also please excuse me, I have dealt with javascript occasionally until now.
IMHO, it could be useful to others. I would want to use any/one/all -Of, in a way similar to how required is used. To have a bit more flexibility in defining schema - generating records such:
basicAccount {"id": _id, "firstName": _firstName...}
then construct records such as employee and customer, and whoever on-top of basicAccount. I can check for employee vs customer easily by doing doing A in B checks. This is my use-case, anyway.
Is there a better way to do what I need without "new semantics"? I will read-up on JSON-schema standards. Thank you. Perhaps, I am not describing it right and in-fact your package would do what I need already, if only I knew how to ask.

**Comment by pateketrueke** [comment]
Could you have a gist with the related schemas and json samples?

I'm trying to understand and some code would help a lot.

**Comment by powerslave** [comment]
### `oneOf` on properties
```json
{
  "oneOf" :[{
    "type": "number",
    "minimum" : 8,
    "maximum": 10
  },{
    "type": "number",
    "minimum":7,
    "maximum": 9
  }]
}
```
json-schema-faker can result `9` from the schema below.

`9` however is not valid, because it matches both of the `oneOfs`, whereas `oneOf` must only match one (in contrast to `anyOf`)





### `oneOf` wrapping `required`
```json
{
  "properties":{
    "one":{
      "type":"string"
    },
    "two": {
      "type":"string"
    }
  },
  "oneOf" :[{
    "required": ["one"]
  },{
    "required": ["two"]
  }]
}
```

schema below can generate
```json
{
  "two": "occaecat Lorem reprehenderit Ut officia",
  "one": "ut minim"
}
```

which is not valid, because it matches both `required`s in `oneOf`, but not more than one must match.





both failing validation cases verified with [ajv](https://github.com/epoberezkin/ajv) and http://www.jsonschemavalidator.net/



----------------

Just found *json-schema-faker*, and was very excited to try it out
Unfortunately our schema relies heavily on such oneOfs like above, and Json-schema-faked data does not validate against the schema, which is a bummer.

Happy to help with more details or snippets if desired.

**Comment by u982744** [comment]
IMHO none of what is listed here is a JSF bug. 

- "anyOf" means one or more, not none or more.
- If you have overlapping "anyOf" or "oneOf" potential values I think that you should just fix so they don't overlap rather than expect JSF to automatically resolve this for you.

**Comment by pateketrueke** [comment]
> Happy to help with more details or snippets if desired.

Please, I want to understand.

> IMHO none of what is listed here is a JSF bug.

Totally agree!

This means that validating against `oneOf` the value should match exactly one schema, if it matches more than one is not valid.

While the `anyOf` validation is not exhaustive on trying all schemas.

On the `jsf` side the only thing we're doing is picking one schema from `anyOf/oneOf` randomly.

**Comment by powerslave** [comment]
To my knowledge, both patterns a) and b), listed in [this comment above](https://github.com/json-schema-faker/json-schema-faker/issues/84#issuecomment-252046015) are allowed by json-schema. AFAIK json-schema does not enforce any rules regarding overlapping values in subschemas.

If it is a good idea to do so is another question. I agree that case a) (from above) is probably not used a lot. I'm convinced however that b) (`oneOf` wrapping `required`) is a common pattern, even more, I think it's the only way to describe certain schemas.

To motivate this, a more concrete example for b): Color definition via either hex string or rgb array.
the color property can be defined by either `hexString`, or `rgbArray`. One of the two is required, but both can not be there (would be overdefined)

```json
{
  "properties":{
    "hexString":{
      "type":"string"
    },
    "rgbArray": {
      "type":"array"
    }
  },
  "oneOf" :[{
    "required": ["hexString"]
  },{
    "required": ["rgbArray"]
  }]
}
```

--------------------

The current implementation
> picking one schema from anyOf/oneOf randomly.  

basically does a anyOf in all cases.

The correct implementation of `oneOf` for `jsf` is not trivial I think. 

i. A brute-force approach could be to keep the random pick, but then validate the result against the schema, and if it doesn't validate, regenerate until it validates. The chance of randomly creating schema-valid json however drastically drops as soon as the schema has various `oneOf`s down the subschema tree, i.e. the number of required regenerations until a "lucky" hit might become uncappetbaly high.

ii. For the proper solution, `jsf` would need to check neighboring oneOfs before populating the picked oneOf, ensuring no other oneOf conidtion is fullfilled. I assume this requires at least partial implementation of what a validator does.

-------------------

`allOf` (not discussed so far) poses very similar challenges like `oneOf`: All subschemas of a `allOf` need to be taken into consideration when generating the `jsf` output.

**Comment by pateketrueke** [comment]
Things are getting complex, effectively as hard as implementing the `not` keyword.

I would like to say that "only valid schemas" are supported by `jsf` otherwise we'll still failing on this topic... until we implement a kind of validation, etc.

BTW; I'm testing your schema on `develop` and didn't work... yet.

**Comment by pateketrueke** [comment]
> Json-schema-faked data does not validate against the schema, which is a bummer.

Well... yeah, JSF will not validate anything, sorry. 

Unfortunately in order to generate a valid schema as output, you must provide a valid schema as input, JSF will try to fake anything it understands and nothing else.

To make this more evident, if you enable `alwaysFakeOptionals` you'll get all properties from the schema.
